#!/bin/bash
cd "$(dirname "$0")"
read -p "Name of the repository folder : " folder
echo "> git submodule deinit -f module"
git submodule deinit -f ./$folder
echo "> git rm -r --cached module"
git rm -r --cached ./$folder
echo "> rm -rf .git/modules/module"
rm -rf .git/modules/$folder
echo "> rm -rf module"
rm -rf ./$folder
